# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Aawara | आवारा"
description: > # this means to ignore newlines until "email:"
   aawara

#email: k[dot]lohani[01]@[google email service provider]
#blog logo
logo: "/assets/images/kshitij_profile_pic_sf_gbridge.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Kshitij Raj Lohani'
author: 'Kshitij Raj Lohani'
author_image: "/assets/images/kshitij_profile_pic.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@kshitij_lohani'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	facebook
    url:	http://facebook.com/aawara.org
    desc: Connect with me facebook

  - icon:	twitter
    url:	https://twitter.com/kshitij_lohani
    desc: Follow me on twitter

  - icon:	youtube
    url:	https://www.youtube.com/user/420kshitij/
    desc: Subscribe my channel
